### ISSUE TITLE
Expressions in code and paper do not match

### ISSUE THREAD

**Issue by youngjaean** [elias-ramzi/ROADMAP#12]
Hello. Thank you for your paper

I read and check the your paper and code. i found the not match Equation (4) and step_rank code in smooth_rank_ap.py line i51 

you are write equaton about 
<img width="471" alt="image" src="https://user-images.githubusercontent.com/30186158/199432833-18717bcc-8dc7-4ac4-bf0c-7288a1bbc61f.png"> but i don`t found (t-delta) in code 

so why don`t made (t-delta) and  sigmoid ??    cod write just ''' tens[~target & pos_mask & margin_mask] = rho * tens[~target & pos_mask & margin_mask] + offset'''  

i don`t understand. Thanks for the explanation

**Comment by elias-ramzi** [comment]
Hi,

line 36 we define `pos_mask = (tens > 0).bool()`, this masks encodes the information `t > 0`.
line 47 we define `margin_mask = tens > delta`, this masks encodes the information `t > detla`.

On line 53 `tens[~target & neg_mask] = tau_sigmoid(tens[~target & neg_mask], tau_n).type(tens.dtype)` we apply the sigmoid for scaller smaller than 0, this is the first line of Eq. (4).
On line 48 we apply the sigmoid `tens[~target & pos_mask & ~margin_mask] = start + tau_sigmoid(tens[~target & pos_mask & ~margin_mask], tau_p).type(tens.dtype)` because we use `~margine_mask` (so when `t` is smaller than delta), this is the second line of Eq. (4).
On line 51 we apply the linear function `tens[~target & pos_mask & margin_mask] = rho * tens[~target & pos_mask & margin_mask] + offset` with `margin_mask` so scallars greater than `delta`, this is the last line of Eq. (4).

Hope this helps!

Don't hesitate to ask more questions if necessary.

Elias

**Comment by youngjaean** [comment]
thx for answer but i dont still understand about last line of Eq.4.

in the paper, you say  rho*(tens - delta) + sigmoid(delta/tau) + 0.5. But in the code, you don't use tens-delta and sigmoid.

so   you say ' linear function'  i don't understand point.

cloud you explain this?  

Actually i don't know why matching from linear function to line 51 code

**Comment by elias-ramzi** [comment]
The last line of Eq. (4) is a linear function. 
We use `sigmoid(delta/tau)` in Eq. (4) as the offset of the linear function.
In my code line 51 all of this is in the `offset` scalar, which is `offset=sigmoid(delta/tau)+0.5`.
But your are right line 51 should be `tens[~target & pos_mask & margin_mask] = rho * (tens[~target & pos_mask & margin_mask]-delta) + offset`. I will correct that.
Thank you for pointing this out!

**Comment by youngjaean** [comment]
good thx  i understand this code 

i think u r very kind :)

have a good day
